/**
 * Pre-populated operational defaults for eRTMAC-NWIS dashboard.
 * Ensures instant first-frame render with zero loading flash or blank screens.
 */
import { DashboardData, SimulationState, Well, SimilarWellResult } from "../types";

export const INITIAL_SIMULATION_STATE: SimulationState = {
  active_well_id: 64,
  active_well_name: "OIL-X123",
  current_depth: 3050.0,
  is_running: true,
  speed_multiplier: 1.0,
  start_depth: 3000.0,
  current_rop: 12.4,
  current_wob: 14.2,
  current_rpm: 110,
  current_torque: 18.2,
  current_pressure: 2950,
  current_mud_flow: 650,
  current_hook_load: 185,
  current_inclination: 2.1,
  current_azimuth: 45.0,
  updated_at: new Date().toISOString(),
  overall_risk: {
    level: "HIGH",
    active_zone_count: 1,
    approaching_count: 2,
    highest_severity: "HIGH",
    summary: "Active Barail formation transition with elevated torque and offset mud loss history.",
  },
};

export const INITIAL_DASHBOARD_DATA: DashboardData = {
  active_well: {
    well_id: "OIL-X123",
    name: "Oil India Well X123 (Active)",
    formation: "Tipam Sandstone",
    total_depth: 3850.0,
    trajectory_type: "DIRECTIONAL",
    latitude: 27.2000,
    longitude: 95.1000,
  },
  simulation: INITIAL_SIMULATION_STATE,
  current_depth: 3050.0,
  kpis: {
    nearby_wells_count: 25,
    historical_events_count: 114,
    high_risk_zones_count: 3,
    top_similarity_score: 91.0,
    top_similar_well: "OIL-X104",
  },
  current_risk: {
    score: 74,
    severity: "HIGH",
    message: "Approaching Barail Transition (3,100m) — High Mud Loss & Differential Sticking Risk",
    active_zones: 1,
    active_event_types: ["MUD_LOSS", "TORQUE_SPIKE"],
  },
  risk_zones: [
    {
      formation: "Tipam Sandstone",
      depth_start: 2980,
      depth_end: 3080,
      event_type: "TORQUE_SPIKE",
      risk_type: "TORQUE_SPIKE",
      severity: "MEDIUM",
      probability: 0.65,
      risk_score: 55,
      description: "Coarse sand stringers causing erratic torque variations.",
      explanation: "Offset wells OIL-X101 and OIL-X104 experienced 18-24 kft-lb torque spikes in this interval.",
      recommended_action: "Monitor RPM variations, optimize WOB to 12-14 klb, maintain stable mud rheology.",
      source_wells: ["OIL-X101", "OIL-X104"],
      status: "CURRENT",
    },
    {
      formation: "Barail Transition",
      depth_start: 3100,
      depth_end: 3250,
      event_type: "MUD_LOSS",
      risk_type: "MUD_LOSS",
      severity: "HIGH",
      probability: 0.82,
      risk_score: 78,
      description: "Depleted sub-interval with high seepage losses observed in offset wells.",
      explanation: "Well OIL-X104 experienced 44 hrs NPT due to severe partial losses (45 bbl/hr) at 3,140m.",
      recommended_action: "Pre-mix LCM pills (25-30 ppb medium nut plug + mica), reduce pump rate before 3,120m.",
      source_wells: ["OIL-X104", "OIL-X108"],
      status: "APPROACHING",
    },
    {
      formation: "Barail Arenaceous",
      depth_start: 3320,
      depth_end: 3450,
      event_type: "STUCK_PIPE",
      risk_type: "STUCK_PIPE",
      severity: "CRITICAL",
      probability: 0.76,
      risk_score: 88,
      description: "Permeable sand overlying reactive shale prone to differential sticking.",
      explanation: "OIL-X102 suffered 68 hrs NPT fishing BHA after differential sticking at 3,380m.",
      recommended_action: "Keep drillstring moving continuously during connections. Restrict static time to < 3 mins.",
      source_wells: ["OIL-X102", "OIL-X104"],
      status: "UPCOMING",
    },
  ],
  top_similar_well: {
    well_id: "OIL-X104",
    name: "Oil India Well X104",
    latitude: 27.266,
    longitude: 95.145,
    distance_km: 8.4,
    formation: "Tipam Sandstone",
    total_depth: 3850.0,
    trajectory_type: "DIRECTIONAL",
    mud_weight: 10.9,
    similarity_score: 0.91,
    similarity_percent: 91.0,
    score_breakdown: {
      formation_match: 0.30,
      depth_proximity: 0.25,
      trajectory_match: 0.20,
      mud_weight_match: 0.15,
      distance_proximity: 0.10,
    },
    event_count: 5,
    total_npt: 44.0,
    factors: {
      distance: 0.88,
      formation: 1.0,
      depth: 0.98,
      trajectory: 1.0,
      parameters: 0.92,
    },
  },
  similar_wells: [
    {
      well_id: "OIL-X104",
      name: "Oil India Well X104",
      latitude: 27.266,
      longitude: 95.145,
      distance_km: 8.4,
      formation: "Tipam",
      total_depth: 3850,
      trajectory_type: "DIRECTIONAL",
      mud_weight: 10.9,
      similarity_score: 0.91,
      similarity_percent: 91,
      score_breakdown: { formation_match: 0.3, depth_proximity: 0.25, trajectory_match: 0.2, mud_weight_match: 0.15, distance_proximity: 0.1 },
      event_count: 5,
      total_npt: 44,
    },
    {
      well_id: "OIL-X101",
      name: "Oil India Well X101",
      latitude: 27.245,
      longitude: 95.120,
      distance_km: 5.2,
      formation: "Tipam",
      total_depth: 3720,
      trajectory_type: "DIRECTIONAL",
      mud_weight: 10.6,
      similarity_score: 0.88,
      similarity_percent: 88,
      score_breakdown: { formation_match: 0.3, depth_proximity: 0.24, trajectory_match: 0.2, mud_weight_match: 0.14, distance_proximity: 0.1 },
      event_count: 4,
      total_npt: 31,
    },
  ],
  recent_alerts: [],
};

export const INITIAL_WELLS: Well[] = [
  {
    id: 64,
    well_id: "OIL-X123",
    name: "Oil India Well X123 (Active)",
    latitude: 27.2000,
    longitude: 95.1000,
    field: "Duliajan Field",
    formation: "Tipam",
    total_depth: 3850.0,
    well_type: "Development",
    trajectory_type: "DIRECTIONAL",
    status: "ACTIVE",
    is_active: true,
    mud_weight: 10.8,
    operator: "Oil India Limited",
  },
  {
    id: 65,
    well_id: "OIL-X104",
    name: "Oil India Well X104",
    latitude: 27.2660,
    longitude: 95.1450,
    field: "Duliajan Field",
    formation: "Tipam",
    total_depth: 3850.0,
    well_type: "Development",
    trajectory_type: "DIRECTIONAL",
    status: "COMPLETED",
    is_active: false,
    mud_weight: 10.9,
    operator: "Oil India Limited",
    distance_km: 8.4,
  },
  {
    id: 66,
    well_id: "OIL-X101",
    name: "Oil India Well X101",
    latitude: 27.2450,
    longitude: 95.1200,
    field: "Duliajan Field",
    formation: "Tipam",
    total_depth: 3720.0,
    well_type: "Development",
    trajectory_type: "DIRECTIONAL",
    status: "COMPLETED",
    is_active: false,
    mud_weight: 10.6,
    operator: "Oil India Limited",
    distance_km: 5.2,
  },
];
